/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'elder',
    path: '/elder',
    component: 'layout.base',
    meta: {
      title: 'elder',
      i18nKey: 'route.elder'
    },
    children: [
      {
        name: 'elder_list',
        path: '/elder/list',
        component: 'view.elder_list',
        meta: {
          title: 'elder_list',
          i18nKey: 'route.elder_list'
        }
      }
    ]
  },
  {
    name: 'evaluation',
    path: '/evaluation',
    component: 'layout.base',
    meta: {
      title: 'evaluation',
      i18nKey: 'route.evaluation'
    },
    children: [
      {
        name: 'evaluation_list',
        path: '/evaluation/list',
        component: 'view.evaluation_list',
        meta: {
          title: 'evaluation_list',
          i18nKey: 'route.evaluation_list'
        }
      }
    ]
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base',
    meta: {
      title: 'finance',
      i18nKey: 'route.finance'
    },
    children: [
      {
        name: 'finance_settlement',
        path: '/finance/settlement',
        component: 'view.finance_settlement',
        meta: {
          title: 'finance_settlement',
          i18nKey: 'route.finance_settlement'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base',
    meta: {
      title: 'order',
      i18nKey: 'route.order'
    },
    children: [
      {
        name: 'order_list',
        path: '/order/list',
        component: 'view.order_list',
        meta: {
          title: 'order_list',
          i18nKey: 'route.order_list'
        }
      }
    ]
  },
  {
    name: 'provider',
    path: '/provider',
    component: 'layout.base',
    meta: {
      title: 'provider',
      i18nKey: 'route.provider'
    },
    children: [
      {
        name: 'provider_list',
        path: '/provider/list',
        component: 'view.provider_list',
        meta: {
          title: 'provider_list',
          i18nKey: 'route.provider_list'
        }
      }
    ]
  },
  {
    name: 'staff',
    path: '/staff',
    component: 'layout.base',
    meta: {
      title: 'staff',
      i18nKey: 'route.staff'
    },
    children: [
      {
        name: 'staff_list',
        path: '/staff/list',
        component: 'view.staff_list',
        meta: {
          title: 'staff_list',
          i18nKey: 'route.staff_list'
        }
      }
    ]
  },
  {
    name: 'statistics',
    path: '/statistics',
    component: 'layout.base',
    meta: {
      title: 'statistics',
      i18nKey: 'route.statistics'
    },
    children: [
      {
        name: 'statistics_finance',
        path: '/statistics/finance',
        component: 'view.statistics_finance',
        meta: {
          title: 'statistics_finance',
          i18nKey: 'route.statistics_finance'
        }
      },
      {
        name: 'statistics_order',
        path: '/statistics/order',
        component: 'view.statistics_order',
        meta: {
          title: 'statistics_order',
          i18nKey: 'route.statistics_order'
        }
      }
    ]
  }
];
